# coding: utf-8

"""
    Template web service

    This is a template of a web service

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from template_web_client.api.items_api import ItemsApi


class TestItemsApi(unittest.TestCase):
    """ItemsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ItemsApi()

    def tearDown(self) -> None:
        pass

    def test_items_create(self) -> None:
        """Test case for items_create

        Create an item
        """
        pass

    def test_items_delete_item(self) -> None:
        """Test case for items_delete_item

        Delete an item
        """
        pass

    def test_items_read_all(self) -> None:
        """Test case for items_read_all

        Read all items
        """
        pass

    def test_items_read_item(self) -> None:
        """Test case for items_read_item

        Read an item
        """
        pass

    def test_items_update_item(self) -> None:
        """Test case for items_update_item

        Update an item
        """
        pass


if __name__ == '__main__':
    unittest.main()
