apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: PHEROMONE_THRESHOLD
            value: "{{ .Values.envVariables.pheromoneThreshold }}"
          - name: METADATA_SERVICE_URL
            value: "{{ .Values.envVariables.metadataService.url }}"
          - name: METADATA_SERVICE_PORT
            value: "{{ .Values.envVariables.metadataService.port }}"
          - name: PHEROMONE_EVAPORATION
            value: "{{ .Values.envVariables.pheromoneEvaporation }}"
          - name: W_EXPLOIT
            value: "{{ .Values.envVariables.wExploit }}"
          - name: BETA
            value: "{{ .Values.envVariables.beta }}"
          - name: W_D
            value: "{{ .Values.envVariables.wD }}"
          - name: T_MAX
            value: "{{ .Values.envVariables.tMax }}"
          - name: R_MAX
            value: "{{ .Values.envVariables.rMax }}"
          - name: REMOVE_VISITATION_THRESHOLD
            value: "{{ .Values.envVariables.removeVisitationThreshold }}"
          - name: NUM_DATASETS
            value: "{{ .Values.envVariables.numDatasets }}"
        - name: scheduled-events
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "app/schedule_events.py"]
          env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: PHEROMONE_THRESHOLD
            value: "{{ .Values.envVariables.pheromoneThreshold }}"
          - name: METADATA_SERVICE_URL
            value: "{{ .Values.envVariables.metadataService.url }}"
          - name: METADATA_SERVICE_PORT
            value: "{{ .Values.envVariables.metadataService.port }}"
          - name: PYTHONPATH
            value: "/code"
          - name: PHEROMONE_EVAPORATION
            value: "{{ .Values.envVariables.pheromoneEvaporation }}"
          - name: W_EXPLOIT
            value: "{{ .Values.envVariables.wExploit }}"
          - name: BETA
            value: "{{ .Values.envVariables.beta }}"
          - name: W_D
            value: "{{ .Values.envVariables.wD }}"
          - name: T_MAX
            value: "{{ .Values.envVariables.tMax }}"
          - name: R_MAX
            value: "{{ .Values.envVariables.rMax }}"
          - name: REMOVE_VISITATION_THRESHOLD
            value: "{{ .Values.envVariables.removeVisitationThreshold }}"
          - name: NUM_DATASETS
            value: "{{ .Values.envVariables.numDatasets }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
