from typing import Any, Dict

import json
import random
import re
from datetime import datetime, timezone
from os import getenv, path
from time import time
from urllib.parse import urlencode

import requests
from loguru import logger
from rdflib.plugins.sparql.parser import parseQuery

from app.schemas import EMPTY_SEARCH_RESPONSE, Message, SearchResponse

# from app.schemas import (
#     ResponseHead,
#     ResponseResults,
#     SearchResponse,
#     SPARQLQuery,
#     UpdateRequestBody,
# )


METADATA_SERVICE_URL = (
    f"http://{getenv('METADATA_SERVICE_URL', 'metadata-service')}:"
    f"{getenv('METADATA_SERVICE_PORT', '80')}"
)
PHEROMONE_THRESHOLD = float(getenv("PHEROMONE_THRESHOLD", "1e-10"))


class SwarmAgent:
    def __init__(self, message: Message, parameters_file: str):
        """
        The function initializes an object with a query, parameters loaded from a file
        and a keyword is derived from the query.

        :param query: The `query` parameter is a string that represents the search query
        in SPARQL language
        :type query: str
        :param parameters_file: The `parameters_file` is a file containing the
        parameters needed for the query. When the `__init__` method is called, the
        `load_parameters` method is used to load these parameters from the specified
        file. File is in json format which is basically a dictionary
        :type parameters_file: str
        """
        self.type = message.message_type
        self.latency = message.time_received - message.time_sent
        self.this_node = getenv("MY_POD_NAME", "swarm-agent")
        self.this_node_ip = getenv("MY_POD_IP", "localhost")
        self.query = message.sparql_query
        self.results = message.results
        self.parameters = self.load_parameters(parameters_file)
        self.keyword = (
            self.transform_query_to_keyword(self.query)
            if message.keyword == ""
            else message.keyword
        )
        self.visited_nodes = message.visited_nodes
        self.link_costs = message.link_costs
        now_utc = datetime.now(timezone.utc)
        self.unique_id = (
            now_utc.strftime("%Y-%m-%d %H:%M:%S.%f")
            if message.unique_id == ""
            else message.unique_id
        )
        self.time_to_live = message.time_to_live  # self.parameters["ttl"]
        self.neighbors = self.get_swarm_agent_neighbors()
        self.pheromone_table: Dict[str, Any] = {}

    def load_parameters(self, file_path: str) -> Any:
        """
        The `load_parameters` function reads and loads parameters from a JSON file into
        a dictionary.

        :param file_path: The `load_parameters` function takes a file path as input and
        reads the contents of the file using the `json.load` method. It then returns the
        loaded data as a dictionary
        :type file_path: str
        :return: The `load_parameters` method is returning a dictionary containing the
        parameters loaded from the JSON file specified by the `file_path` argument.
        """
        if not path.exists(file_path):
            raise FileNotFoundError(f"The file {file_path} does not exist.")
        with open(file_path, "r") as file:
            return json.load(file)

    def transform_query_to_keyword(self, query):
        """
        The function `transform_query_to_keyword` extracts keywords from a query string.

        :param query: the function `transform_query_to_keyword` is designed to extract
        specific parts from a query string and transform them into a keyword. The
        function uses regular expressions to find text within curly braces `{}` in the
        query string, then processes and concatenates certain parts of the extracted
        text to form the
        :return: The function `transform_query_to_keyword` returns a keyword based on
        the input query. The keyword is generated by extracting specific parts of the
        query and combining them in a certain way.
        """

        pattern = r"\{([^}]*)\}"

        matches = re.findall(pattern, query)

        match_arr = matches[0].replace("\n", "").replace(".", "").split(" ")
        match_clean_arr = [s for s in match_arr if s]
        raw_sub, raw_pre, raw_obj = match_clean_arr

        sub = raw_sub if raw_sub[0] != "?" else ""

        pre = re.sub(r"[<>]", "", raw_pre).split("/")[-1] if raw_pre[0] != "?" else ""

        obj = raw_obj.split("^^")[0].replace('"', "") if raw_obj[0] != "?" else ""

        keyword = "_".join(filter(None, [sub, pre, obj]))
        if keyword == "":
            keyword = "all"

        return keyword

    def get_swarm_agent_neighbors(self):
        """
        The function retrieves the neighbors of a swarm agent from a graph database.
        :return: A list of dictionaries containing the name and IP address of
        neighboring swarm agents.
        """
        query = f"""SELECT ?neighbor WHERE {{
            GRAPH <swarm-agent:neighbors> {{
                <{self.this_node}:{self.this_node_ip}> <swarm:isNeighborOf> ?neighbor
            }}
        }}"""

        results = self.local_query(query)

        swarm_agents = []
        for result in results.results.bindings:
            name, ip = result["neighbor"]["value"].split(":")
            swarm_agents.append({"name": name, "ip": ip})

        return swarm_agents

    def get_triples_from_query(self, sparql_query):
        parsed_query = parseQuery(sparql_query)
        triple_pattern = parsed_query[1]["where"]["part"][0]["triples"][0]
        predicate = triple_pattern[1]["part"][0]["part"][0]["part"]
        local_predicate = predicate.split("/")[-1]

        local_object = str(triple_pattern[2]["string"])

        return local_predicate, local_object

    def local_query(self, query: str | None = None) -> SearchResponse:
        """
        Queries Local Metadata service
        """
        if query is None:
            query = self.query

        params = {"query": query}
        encoded_query = urlencode(params)
        base_url = f"{METADATA_SERVICE_URL}/api/v0/graph"
        full_url = f"{base_url}?{encoded_query}"

        try:
            response = requests.get(full_url)
        except Exception as e:
            logger.error(str(e))
            raise e

        if response.status_code == 200:
            return SearchResponse.model_validate_json(response.text)
        else:
            logger.error(f"Error: {response.status_code}, {response.text}")

        return EMPTY_SEARCH_RESPONSE

    def get_pheromone_table(self, this_node: str) -> dict[str, Any]:
        logger.debug("I am reading from pheromone table...")
        pheromone_query = f"""
        SELECT ?keyword ?neighbor_id ?pheromone_value
        WHERE {{
            GRAPH <swarm-agent:pheromones> {{
                <swarm:{this_node}> <swarm:hasAssociation> ?assoc .
                ?assoc <swarm:hasKeyword> ?keyword ;
                        <swarm:hasNeighbor> ?neighbor_id ;
                        <swarm:hasPheromoneValue> ?pheromone_value .
            }}
        }}"""

        results = self.local_query(pheromone_query)
        pheromone_table: dict[str, Any] = {}

        for result in results.results.bindings:
            logger.debug(
                "I have found keyword {keyword} for neighbor {nbr}",
                keyword=result["keyword"]["value"],
                nbr=result["neighbor_id"]["value"],
            )
            try:
                pheromone_table[result["keyword"]["value"]][
                    result["neighbor_id"]["value"]
                ] = float(result["pheromone_value"]["value"])
            except KeyError:
                pheromone_table[result["keyword"]["value"]] = {
                    result["neighbor_id"]["value"]: float(
                        result["pheromone_value"]["value"]
                    )
                }

        return pheromone_table

    def delete_pheromone_entry(self, local_node_id, keyword, neighbor_id):
        pheromone_delete_query = f"""
        DELETE {{
        GRAPH <swarm-agent:pheromones> {{
            <swarm:{local_node_id}> <swarm:hasAssociation> ?association .
            ?association <swarm:hasKeyword> "{keyword}" ;
                        <swarm:hasNeighbor> "{neighbor_id}" ;
                        <swarm:hasPheromoneValue> ?pheromoneValue .
            }}
        }}
        WHERE {{
        GRAPH <swarm-agent:pheromones> {{
            <swarm:{local_node_id}> <swarm:hasAssociation> ?association .
            ?association <swarm:hasKeyword> "{keyword}" ;
                        <swarm:hasNeighbor> "{neighbor_id}" ;
                        <swarm:hasPheromoneValue> ?pheromoneValue .
            }}
        }}"""

        params = {"query": pheromone_delete_query}

        response = self.send_message(
            params, METADATA_SERVICE_URL, "api/v0/graph/update"
        )

        return response, pheromone_delete_query

    def add_pheromone_entry(self, local_node_id, keyword, neighbor_id, ph_value):
        association = f"{local_node_id}:" + keyword + "---" + neighbor_id
        pheromone_insert_query = f"""INSERT DATA {{
            GRAPH <swarm-agent:pheromones> {{ <swarm:{local_node_id}>
            <swarm:hasAssociation> <{association}> .
            <{association}>
            <swarm:hasKeyword> "{keyword}" ;
            <swarm:hasNeighbor> "{neighbor_id}" ;
            <swarm:hasPheromoneValue> {ph_value} . }} }}"""

        params = {"query": pheromone_insert_query}

        response = self.send_message(
            params, METADATA_SERVICE_URL, "api/v0/graph/update"
        )

        return response, pheromone_insert_query

    def update_in_two_steps(self, local_node_id, keyword, neighbor_id, ph_value):
        response_delete, pheromone_delete_query = self.delete_pheromone_entry(
            local_node_id, keyword, neighbor_id
        )
        if ph_value > PHEROMONE_THRESHOLD:
            response_add, pheromone_add_query = self.add_pheromone_entry(
                local_node_id, keyword, neighbor_id, ph_value
            )
        else:
            response_add, pheromone_add_query = None, None

        return (
            response_add,
            pheromone_add_query,
            response_delete,
            pheromone_delete_query,
        )

    def getGoodnessValues(self, keyword):
        goodness_values = []

        for neighbor in self.pheromone_table[keyword]:
            goodness_values.append(
                self.pheromone_table[keyword][neighbor] * self.parameters["beta"]
            )

        return goodness_values

    def create_backward_message(
        self, results: SearchResponse, unique_id: str = ""
    ) -> Message:
        message = Message(
            message_type="backward",
            unique_id=unique_id,
            sparql_query=self.query,
            visited_nodes=self.visited_nodes,
            link_costs=self.link_costs,
            time_to_live=(
                len(self.visited_nodes) if unique_id == "" else self.time_to_live - 1
            ),
            keyword=self.keyword,
            results=results,
        )
        logger.debug("from create {message_type}", message_type=message.message_type)
        return message

    def create_forward_message(self) -> Message:
        message = Message(
            message_type="forward",
            unique_id=self.unique_id,
            sparql_query=self.query,
            visited_nodes=self.visited_nodes,
            link_costs=self.link_costs,
            time_to_live=self.time_to_live - 1,
            keyword=self.keyword,
        )
        logger.debug("from create {message_type}", message_type=message.message_type)
        return message

    def send_message(self, message, url, endpoint="api/v0/create_agent"):
        headers = {"Content-Type": "application/json", "accept": "application/json"}
        url = f"{url}/{endpoint}"

        try:
            response = requests.post(url, json=message, headers=headers)
            if response.status_code != 200:
                logger.error(f"Error: {response.status_code}, {response.text}")

            return response
        except Exception as e:
            logger.error(str(e))
            raise e

    def forward_ant_step(self):
        if len(self.visited_nodes) > 0:
            self.link_costs[self.this_node] = self.latency
        self.visited_nodes.append({"name": self.this_node, "ip": self.this_node_ip})
        results = self.local_query()
        self.pheromone_table = self.get_pheromone_table(self.this_node)
        if self.keyword in self.pheromone_table:
            logger.debug(
                "pheromone_table[{keyword}]".format(keyword=self.keyword),
                self.pheromone_table[self.keyword],
            )
        else:
            self.pheromone_table[self.keyword] = {}

            for neighbor in self.neighbors:
                self.pheromone_table[self.keyword][neighbor["name"]] = 0.1
                logger.debug("I am updating the pheromone table...")
                (
                    response_add,
                    pheromone_add_query,
                    response_delete,
                    pheromone_delete_query,
                ) = self.update_in_two_steps(
                    self.this_node,
                    self.keyword,
                    neighbor["name"],
                    self.pheromone_table[self.keyword][neighbor["name"]],
                )

            logger.debug(
                "Add response: {response_add}, delete response: {response_delete}",
                response_add=response_add.json(),
                response_delete=response_delete.json(),
            )

            logger.debug(
                "pheromone_table[{keyword}] = {content}",
                keyword=self.keyword,
                content=self.pheromone_table[self.keyword],
            )

        unvisited_neighbors = self.getUnvisitedNeighbors()

        logger.debug("my neighbors: {}", self.neighbors)
        logger.debug("visited neighbors: {}", self.visited_nodes)
        logger.debug("unvisited neighbors: {}", unvisited_neighbors)

        goodness_values = self.getGoodnessValuesUnvisited(unvisited_neighbors)

        logger.debug(
            "goodness_values={goodness_values}", goodness_values=goodness_values
        )

        logger.debug(
            "self.time_to_live = {time_to_live}", time_to_live=self.time_to_live
        )

        forward_message = self.create_forward_message()

        logger.debug(
            "forward_message.time_to_live = {ttl}", ttl=forward_message.time_to_live
        )

        logger.debug("forward_message = {fm}", fm=forward_message.model_dump())

        if random.random() < self.parameters["w_exploit"]:
            # implementing exploitation
            logger.debug("Exploitation chosen!")
            chosen_nodes = self.exploit(goodness_values, unvisited_neighbors)
        else:
            # implementing exploration
            logger.debug("Exploration chosen!")
            chosen_nodes = self.explore(goodness_values, unvisited_neighbors)

            # chosen_nodes = self.exploit(goodness_values, unvisited_neighbors)
        # return the neighbors where the pheromone levels are higher
        # then the average pheromone level of the neighbors
        logger.debug("chosen nodes: {}", chosen_nodes)

        if forward_message.time_to_live > 0 and len(chosen_nodes) > 0:
            for chosen_node in chosen_nodes:
                logger.debug(
                    "I am sending the message to {node} with IP address {node_ip}",
                    node=chosen_node["name"],
                    node_ip=chosen_node["ip"],
                )
                forward_message.time_sent = time()
                self.send_message(
                    forward_message.model_dump(),
                    f"http://{chosen_node['ip']}:80",
                )
        else:
            visited = "Yes!" if len(unvisited_neighbors) == 0 else "No!"
            logger.debug(
                "Ant terminated! ttl={ttl}, visited all neighbors {visited}",
                ttl=forward_message.time_to_live,
                visited=visited,
            )

        if len(results.results.bindings) > 0:
            backward_message = self.create_backward_message(results)
            backward_message.time_sent = time()
            self.send_message(
                backward_message.model_dump(), f"http://{self.this_node_ip}:80"
            )

        # once proper node is chosen we need to send the message further

        return False, EMPTY_SEARCH_RESPONSE

    def getUnvisitedNeighbors(self):
        unvisited_neighbors = [
            neighbor
            for neighbor in self.neighbors
            if neighbor not in self.visited_nodes
        ]

        return unvisited_neighbors

    def getGoodnessValuesUnvisited(self, unvisited_neighbors):
        goodness_values = []

        for neighbor in unvisited_neighbors:
            goodness_values.append(
                self.pheromone_table[self.keyword][neighbor["name"]]
                * self.parameters["beta"]
            )

        return goodness_values

    def explore(self, goodness_values, unvisited_neighbors):
        total_goodness = sum(goodness_values)
        probabilities = [value / total_goodness for value in goodness_values]
        is_chosen = [random.random() <= prob for prob in probabilities]
        chosen_nodes = [
            neighbor for i, neighbor in enumerate(unvisited_neighbors) if is_chosen[i]
        ]
        if len(chosen_nodes) == 0:
            chosen_nodes = self.exploit(goodness_values, unvisited_neighbors)
        return chosen_nodes

    def exploit(self, goodness_values, unvisited_neighbors):
        mean_goodness = sum(goodness_values) / len(goodness_values)
        logger.debug("mean_goodness = {}", mean_goodness)
        tolerance = 1e-5
        chosen_nodes = [
            node
            for node, goodness in zip(unvisited_neighbors, goodness_values)
            if goodness >= mean_goodness - tolerance
        ]

        return chosen_nodes

    def backward_ant_step(self):
        # hardcoded parameters for now
        w_d = 0.5
        t_max = 3
        r_max = 10

        if len(self.link_costs) > 0 and self.time_to_live < len(self.visited_nodes):
            self.pheromone_table = self.get_pheromone_table(self.this_node)

            total_link_costs = sum(self.link_costs.values())
            z = w_d * len(self.results.results.bindings) / r_max + (
                (1 - w_d) * t_max / (2 * total_link_costs)
            )

            target_neighbor = self.visited_nodes[self.time_to_live]["name"]
            self.update_in_two_steps(
                self.this_node,
                self.keyword,
                target_neighbor,
                self.pheromone_table[self.keyword][target_neighbor] + z,
            )

        if self.time_to_live > 1:
            backward_message = self.create_backward_message(
                self.results, self.unique_id
            )
            backward_message.time_sent = time()
            self.send_message(
                backward_message.model_dump(),
                f"http://{self.visited_nodes[self.time_to_live-2]['ip']}:80",
            )

            return False, EMPTY_SEARCH_RESPONSE

        return True, self.results

    def step(self):
        logger.debug("this_node = {this_node}", this_node=self.this_node)

        if self.type == "forward":
            return self.forward_ant_step()

        return self.backward_ant_step()

    def pheromone_evaporation(self):
        pheromone_table = self.get_pheromone_table(self.this_node)

        for keyword in pheromone_table:
            for neighbor in pheromone_table[keyword]:
                self.update_in_two_steps(
                    self.this_node,
                    keyword,
                    neighbor,
                    pheromone_table[keyword][neighbor] * (1 - self.parameters["p"]),
                )
