image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "swarm-agent"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 80

resources: {}

livenessProbe:
  failureThreshold: 10
  httpGet:
    path: /
    port: http
  periodSeconds: 60
  timeoutSeconds: 40
readinessProbe:
  failureThreshold: 10
  httpGet:
    path: /
    port: http
  periodSeconds: 60
  timeoutSeconds: 40

ingressHostName: swarm-agent

envVariables:
  pheromoneThreshold: 1e-5
  metadataService:
    url: metadata-service
    port: 80
  pheromoneEvaporation: 0.1
  removeVisitationThreshold: 86400000

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 100%
