image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 80

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
  periodSeconds: 60
  timeoutSeconds: 40
readinessProbe:
  httpGet:
    path: /
    port: http
  periodSeconds: 60
  timeoutSeconds: 40

ingressHostName: swarm-agent

envVariables:
  pheromoneThreshold: 1e-5
  metadataService:
    url: metadata-service
    port: 80
